export const applicationTypes = Object.freeze({
  GET_APPLICATION: 'GET_APPLICATION',
  REMOVE_APPLICATION: 'REMOVE_APPLICATION',
  GET_VIDEO_COMMENTS: 'GET_VIDEO_COMMENTS',
  POST_VIDEO_COMMENTS: 'POST_VIDEO_COMMENTS'
});
